# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: mwaldstein.qipu
PackageVersion: 0.3.32
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: qipu.exe
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/mwaldstein/qipu/releases/download/v0.3.32/qipu-0.3.32-x86_64-pc-windows-msvc.zip
    InstallerSha256: "0000000000000000000000000000000000000000000000000000000000000000"
ManifestType: installer
ManifestVersion: 1.6.0
# TODO: Update InstallerSha256 after release assets are published (see qipu-j013)
